---
- name: Configuration of microk8s
  hosts: control_plan
  gather_facts: true
  become: false
  vars_files:
    "../group_vars/{{ env }}/microk8s.yml"
  tasks:
    - name: Ensure .kube directory exists on {{ ansible_env.HOME }}
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: '777'

    - name: Activate microk8s addOns
      ansible.builtin.shell: |
        sudo usermod -a -G microk8s $USER
        sudo chown -R $USER ~/.kube
        sudo microk8s config > ~/.kube/config
        microk8s start
        # AddOns
        sudo microk8s enable ingress
        sudo microk8s enable community
        sudo microk8s enable cert-manager
        sudo microk8s enable storage
        sudo microk8s enable metallb:"{{ cidr }}"
      register: microk8s_result
      changed_when: "'Skipping' not in microk8s_result.stdout"
