---
- name: K9s process installation
  hosts: control_plan
  become: true
  gather_facts: true
  vars_files:
    ../group_vars/k9s.yml
  tasks:
    - name: Download K9s for {{ ansible_facts['distribution'] }}
      ansible.builtin.get_url:
        url: "https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_amd64.tar.gz"
        dest: /tmp/k9s_Linux_amd64.tar.gz
        force: false
        mode: '0644' # pour que le fichier soit lisible par tous les utilisateurs, mais modifiable uniquement par le propriétaire
      when: ansible_facts['architecture'] == 'x86_64'

    - name: Download K9s for {{ ansible_facts['distribution'] }}
      ansible.builtin.get_url:
        url: "https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_arm64.tar.gz"
        dest: /tmp/k9s_Linux_arm64.tar.gz
        force: false
        mode: '0644'
      when: ansible_facts['architecture'] == 'aarch64'

    - name: Install k9s for {{ ansible_facts['distribution'] }}
      ansible.builtin.shell: |
        cd /tmp/
        #wget "https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_amd64.tar.gz"
        tar -xzvf k9s_Linux_amd64.tar.gz
        sudo install k9s /usr/local/bin/
      when: ansible_facts['architecture'] == 'x86_64'
      register: k9s_installl_result
      changed_when: "'Skipping' not in k9s_installl_result.stdout"

    - name: Install k9s for {{ ansible_facts['distribution'] }}
      ansible.builtin.shell: |
        cd /tmp/
        #wget "https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_arm64.tar.gz"
        tar -xzvf k9s_Linux_arm64.tar.gz
        sudo install k9s /usr/local/bin/
      when: ansible_facts['architecture'] == 'aarch64'
      register: k9s_installl_result
      changed_when: "'Skipping' not in k9s_installl_result.stdout"

    - name: Verify k9s installation for {{ ansible_facts['distribution'] }}
      ansible.builtin.shell: |
        k9s version | grep Version
      register: k9s_version
      changed_when: false

    - name: Debug k9s version for {{ ansible_facts['distribution'] }}
      ansible.builtin.debug:
        msg: "{{ k9s_version.stdout }}"
